services:
  - type: web
    name: myfaceclone
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: uvicorn MyFaceclone.asgi:application --host 0.0.0.0 --port $PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_USE_MANIFEST_STATIC
        value: "True"
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com