from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('home', views.home,name='home'),
    path('explore', views.explore, name='explore'),
    path('reels', views.reels, name='reels'),
    path('saved', views.saved_posts, name='saved-posts'),
    path('notifications', views.notifications_view, name='notifications'),
    path('notifications/read', views.mark_notifications_read, name='notifications-read'),
    path('theme/toggle', views.toggle_theme, name='toggle-theme'),
    path('profile', views.profile, name='profile'),
    path('profile/<str:username>', views.profile, name='profile-user'),
    path('chat', views.chat, name='chat'),
    path('chat/group/create', views.create_group, name='create-group'),
    path('chat/group/<int:group_id>', views.group_chat, name='group-chat'),
    path('chat/group/<int:group_id>/send', views.send_group_message, name='send-group-message'),
    path('chat/send', views.send_message, name='send-message'),
    path('logout', views.signout, name='logout'),
    path('register', views.register, name='register'),
    path('update', views.update_profile, name='update'),
    path('addpost', views.create_post, name='addpost'),
    path('post/<int:post_id>/delete', views.delete_post, name='delete-post'),
    path('post/<int:post_id>/like', views.toggle_like, name='toggle-like'),
    path('post/<int:post_id>/save', views.toggle_save_post, name='toggle-save-post'),
    path('post/<int:post_id>/comment', views.add_comment, name='add-comment'),
    path('story/create', views.create_story, name='create-story'),
    path('follow/<str:username>/toggle', views.toggle_follow, name='toggle-follow'),
    path('block/<str:username>/toggle', views.toggle_block, name='toggle-block'),
    path('friend/<str:username>/send', views.send_friend_request, name='send-friend-request'),
    path('friend/request/<int:friendship_id>/<str:action>', views.respond_friend_request, name='respond-friend-request'),
    path('friend/<str:username>/unfriend', views.unfriend, name='unfriend'),
]
